name: holz_logistik
description: A logistics app for wood trading
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  crypto: ^3.0.6
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_image_slideshow: ^0.1.6
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  holz_logistik_backend:
    path: holz_logistik_backend
  image_picker: ^1.1.2
  intl: any
  latlong2: ^0.9.1
  location: ^8.0.0
  multi_dropdown: ^3.0.1
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  stream_transform: ^2.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^1.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
