name: holz_logistik_backend
description: A flutter implementation of the apis, local_storage, repositories and sync services holz logistik uses.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  meta: ^1.7.0
  path: ^1.9.1
  rxdart: ^0.28.0
  shared_preferences: ^2.0.0
  sqflite: ^2.4.2
  uuid: ^3.0.6
  web_socket_channel: ^3.0.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
